language: node_js
node_js:
  - "stable"
before_script:
  - make build
script:
  - make test
notifications:
  email: 
    recipients:
      - ruanarcega@gmail.com
    on_success: never
    on_failure: always
